version: "3"

services:
  mysql:
    image: mysql:8.0.23
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: myadmin
    restart: always
    ports:
      - 8888:80
    volumes:
      - ./myadmin/upload.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      MYSQL_ROOT_PASSWORD: ""
      PMA_HOST: mysql
    depends_on:
      - mysql