version: "2"
services:
  postgres:
    image: postgres:13.1
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ''
      POSTGRES_PASSWORD: ''
    
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on: 
      - postgres
    ports: 
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: 'user@domain.com'
      PGADMIN_DEFAULT_PASSWORD: ''