version: '2'
services:
  postgres:
    image: postgres:14.2
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD:
    volumes:
      - ./data:/var/lib/postgresql/data

  admin:
    image: adminer
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8889:8080
